const Menuitems = [
  {
    title: "Management",
    icon: "report",
    href: "/client",
    collapse: true,
    isCLient: true,
    children: [
      {
        title: "Project",
        icon: "all-report",
        href: "/client/client",
        isCLient: true,
      },
      {
        title: "Kandidat JC",
        icon: "absent",
        href: "/client/user-jc",
        isCLient: true,
      },
      {
        title: "Submit Kandidat",
        icon: "users",
        href: "/client/candidate-sent",
        isCLient: true,
      },
      {
        title: "Submit History",
        icon: "book",
        href: "/client/candidate-sent-history",
        isCLient: true,
      },
    ],
  },
  {
    title: "Submit Kandidat",
    icon: "management",
    href: "/client/submit-kandidat",
    collapse: true,
    isCLient: true,
    children: [
      {
        title: "Semua",
        icon: "users",
        href: "/client/submit-kandidat/semua",
        isCLient: true,
      },
      {
        title: "Belum diproses",
        icon: "user",
        href: "/client/submit-kandidat/belum-diproses",
        isCLient: true,
      },
      {
        title: "Proses",
        icon: "user",
        href: "/client/submit-kandidat/proses",
        isCLient: true,
      },
      {
        title: "Test",
        icon: "user",
        href: "/client/submit-kandidat/test",
        isCLient: true,
      },
      {
        title: "Interview",
        icon: "user",
        href: "/client/submit-kandidat/interview",
        isCLient: true,
      },
      {
        title: "Hired",
        icon: "user",
        href: "/client/submit-kandidat/hired",
        isCLient: true,
      },
      {
        title: "Rejected",
        icon: "user",
        href: "/client/submit-kandidat/rejected",
        isCLient: true,
      },
    ],
  },
  {
    title: "Dashboard",
    icon: "dashboard",
    href: "/dashboards/dashboard",
    collapse: true,
    isAdmin: true,
    isSPV: true,
    isStaff: false,
  },
  {
    title: "Management",
    icon: "management",
    href: "/management",
    collapse: true,
    isAdmin: true,
    isStaff: true,
    children: [
      {
        title: "User",
        icon: "users",
        href: "/management/user",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Klien",
        icon: "users",
        href: "/management/client",
        isAdmin: true,
      },
      {
        title: "Kandidat JC",
        icon: "users",
        href: "/management/user-jc",
        isAdmin: true,
      },
      {
        title: "Submit Kandidat",
        icon: "users",
        href: "/management/candidate-sent",
        isAdmin: true,
      },
      {
        title: "Submit History",
        icon: "book",
        href: "/management/candidate-sent-history",
        isAdmin: true,
      },
    ],
  },
  {
    title: "Submit Kandidat",
    icon: "management",
    href: "/submit-kandidat",
    collapse: true,
    isAdmin: true,
    isStaff: true,
    children: [
      {
        title: "Semua",
        icon: "users",
        href: "/submit-kandidat/semua",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Belum diproses",
        icon: "user",
        href: "/submit-kandidat/belum-diproses",
        isAdmin: true,
      },
      {
        title: "Proses",
        icon: "user",
        href: "/submit-kandidat/proses",
        isAdmin: true,
      },
      {
        title: "Test",
        icon: "user",
        href: "/submit-kandidat/test",
        isAdmin: true,
      },
      {
        title: "Interview",
        icon: "user",
        href: "/submit-kandidat/interview",
        isAdmin: true,
      },
      {
        title: "Hired",
        icon: "user",
        href: "/submit-kandidat/hired",
        isAdmin: true,
      },
      {
        title: "Rejected",
        icon: "user",
        href: "/submit-kandidat/rejected",
        isAdmin: true,
      },
    ],
  },
];
export default Menuitems;
