const Menuitems = [
  // {
  //   navlabel: true,
  //   subheader: "MENU",
  //   icon: "mdi mdi-dots-horizontal",
  //   href: "Dashboard",
  //   role: "admin",
  //   isAdmin: true,
  //   isSPV: true,
  //   isStaff: true,
  // },

  // {
  //   title: "Dashboard",
  //   icon: "dashboard",
  //   href: "/dashboards/dashboard",
  //   collapse: true,
  //   isAdmin: true,
  // },
  {
    title: "Laporan",
    icon: "report",
    href: "/client",
    collapse: true,
    isCLient: true,
    children: [
      {
        title: "Semua",
        icon: "all-report",
        href: "/client/all",
        isCLient: true,
      },
      {
        title: "Kehadiran",
        icon: "absent",
        href: "/client/kehadiran",
        isCLient: true,
      },
      {
        title: "Cuti",
        icon: "leave",
        href: "/client/cuti",
        isCLient: true,
      },
      {
        title: "Lembur",
        icon: "overtime",
        href: "/client/lembur",
        isCLient: true,
      },
      {
        title: "Koreksi",
        icon: "correct",
        href: "/client/koreksi",
        isCLient: true,
      },
      {
        title: "Generate",
        icon: "export",
        href: "/client/generate",
        isCLient: true,
      },
    ],
  },
  // {
  //   title: "Laporan",
  //   icon: "report",
  //   href: "/leader",
  //   collapse: true,
  //   isLeader: true,
  //   children: [
  //     {
  //       title: "Semua",
  //       icon: "all-report",
  //       href: "/leader/all",
  //       isLeader: true,
  //     },
  //     {
  //       title: "Kehadiran",
  //       icon: "absent",
  //       href: "/leader/kehadiran",
  //       isLeader: true,
  //     },
  //     {
  //       title: "Cuti",
  //       icon: "leave",
  //       href: "/leader/cuti",
  //       isLeader: true,
  //     },
  //     {
  //       title: "Lembur",
  //       icon: "overtime",
  //       href: "/leader/lembur",
  //       isLeader: true,
  //     },
  //     {
  //       title: "Koreksi",
  //       icon: "correct",
  //       href: "/leader/koreksi",
  //       isLeader: true,
  //     },
  //     {
  //       title: "Generate",
  //       icon: "export",
  //       href: "/leader/generate",
  //       isLeader: true,
  //     },
  //   ],
  // },

  // {
  //   title: "Laporan",
  //   icon: "report",
  //   href: "/laporan",
  //   collapse: true,
  //   isAdmin: true,
  //   isSPV: true,
  //   isStaff: true,
  //   children: [
  //     {
  //       title: "Semua",
  //       icon: "all-report",
  //       href: "/laporan/all",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //     {
  //       title: "Kehadiran",
  //       icon: "absent",
  //       href: "/laporan/activity",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //     {
  //       title: "Izin",
  //       icon: "permit",
  //       href: "/laporan/izin",
  //       role: "admin",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //     {
  //       title: "Izin Terlambat",
  //       icon: "slack",
  //       href: "/laporan/izin-terlambat",
  //       role: "admin",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //     {
  //       title: "Izin Pulang Cepat",
  //       icon: "slack",
  //       href: "/laporan/izin-pulang-cepat",
  //       role: "admin",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },

  //     {
  //       title: "Cuti",
  //       icon: "leave",
  //       href: "/laporan/cuti",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },

  //     {
  //       title: "Sakit",
  //       icon: "sick",
  //       href: "/laporan/sakit",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //     {
  //       title: "Lembur",
  //       icon: "overtime",
  //       href: "/laporan/overtime",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //     {
  //       title: "Perjalanan Dinas",
  //       icon: "business-trip",
  //       href: "/laporan/perjalanan-dinas",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //     {
  //       title: "Koreksi",
  //       icon: "correct",
  //       href: "/laporan/koreksi",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //     {
  //       title: "Generate",
  //       icon: "export",
  //       href: "/laporan/generate",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //   ],
  // },

  {
    title: "Management",
    icon: "management",
    href: "/management",
    collapse: true,
    isAdmin: true,
    isStaff: true,
    children: [
      {
        title: "User",
        icon: "users",
        href: "/management/user",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      // {
      //   title: "Pendaftaran User",
      //   icon: "user-plus",
      //   href: "/management/user-v2/register",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Pendaftaran Sendiri",
      //   icon: "self-registration",
      //   href: "/management/self-registration",
      //   isAdmin: true,
      // },
      // {
      //   title: "Divisi",
      //   icon: "globe",
      //   href: "/management/divisi",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Unit",
      //   icon: "globe",
      //   href: "/management/departemens",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Unit Setting",
      //   icon: "settings",
      //   href: "/management/departements-settings",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Posisi",
      //   icon: "position",
      //   href: "/management/position",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      {
        title: "Client Upliner",
        icon: "users",
        href: "/management/client-upliner",
        isAdmin: true,
      },
      // {
      //   title: "Absen Point",
      //   icon: "map-pin",
      //   href: "/management/location-point",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Jabatan",
      //   icon: "briefcase",
      //   href: "/management/job-level",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Shifting",
      //   icon: "shifting",
      //   href: "/management/shifting",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Jadwal",
      //   icon: "calendar",
      //   href: "/management/schedule",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Event Date",
      //   icon: "info",
      //   href: "/management/event-date",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Hari Libur",
      //   icon: "info",
      //   href: "/management/holidays",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      // {
      //   title: "Day Off",
      //   icon: "calendar",
      //   href: "/management/day-off",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
    ],
  },
  // {
  //   title: "Perusahaan",
  //   icon: "company",
  //   href: "/company",
  //   collapse: true,
  //   isSuperAdmin: true,
  //   role: "admin",
  //   isAdmin: true,
  //   isStaff: true,
  //   children: [
  //     {
  //       title: "Perusahaan",
  //       icon: "compass",
  //       href: "/company/add-company",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //     {
  //       title: "Pengaturan Perusahaan",
  //       icon: "settings",
  //       href: "/company/company-setting",
  //       isAdmin: true,
  //       isSPV: true,
  //       isStaff: true,
  //     },
  //   ],
  // },
];
export default Menuitems;
