const Menuitems = [
  {
    title: "Management",
    icon: "users",
    href: "/client",
    collapse: true,
    isCLient: true,
    children: [
      {
        title: "Project",
        icon: "all-report",
        href: "/client/client",
        isCLient: true,
      },
      {
        title: "Kandidat JC",
        icon: "shifting",
        href: "/client/user-jc",
        isCLient: true,
      },
      // {
      //   title: "Submit Kandidat",
      //   icon: "export",
      //   href: "/client/candidate-sent",
      //   isCLient: true,
      // },
      {
        title: "Submit History",
        icon: "book",
        href: "/client/candidate-sent-history",
        isCLient: true,
      },
    ],
  },
  {
    title: "Submit Kandidat",
    icon: "report",
    href: "/client/submit-kandidat",
    collapse: true,
    isCLient: true,
    children: [
      {
        title: "Semua",
        icon: "position",
        href: "/client/submit-kandidat/semua",
        isCLient: true,
      },
      {
        title: "Belum diproses",
        icon: "shifting",
        href: "/client/submit-kandidat/belum-diproses",
        isCLient: true,
      },
      {
        title: "Proses",
        icon: "all-report",
        href: "/client/submit-kandidat/proses",
        isCLient: true,
      },
      {
        title: "Test",
        icon: "permit",
        href: "/client/submit-kandidat/test",
        isCLient: true,
      },
      {
        title: "Interview",
        icon: "export",
        href: "/client/submit-kandidat/interview",
        isCLient: true,
      },
      {
        title: "Hired",
        icon: "correct",
        href: "/client/submit-kandidat/hired",
        isCLient: true,
      },
      {
        title: "Rejected",
        icon: "leave",
        href: "/client/submit-kandidat/rejected",
        isCLient: true,
      },
    ],
  },
  {
    title: "Dashboard",
    icon: "dashboard",
    href: "/dashboards/dashboard",
    collapse: true,
    isAdmin: true,
    isSPV: true,
    isStaff: false,
  },
  {
    title: "Management",
    icon: "management",
    href: "/management",
    collapse: true,
    isAdmin: true,
    isStaff: true,
    children: [
      // {
      //   title: "User",
      //   icon: "position",
      //   href: "/management/user",
      //   isAdmin: true,
      //   isSPV: true,
      //   isStaff: true,
      // },
      {
        title: "Klien",
        icon: "business-trip",
        href: "/management/client",
        isAdmin: true,
      },
      {
        title: "Kandidat JC",
        icon: "absent",
        href: "/management/user-jc",
        isAdmin: true,
      },
      // {
      //   title: "Submit Kandidat",
      //   icon: "position",
      //   href: "/management/candidate-sent",
      //   isAdmin: true,
      // },
      {
        title: "Submit History",
        icon: "company",
        href: "/management/candidate-sent-history",
        isAdmin: true,
      },
    ],
  },
  {
    title: "Submit Kandidat",
    icon: "report",
    href: "/submit-kandidat",
    collapse: true,
    isAdmin: true,
    isStaff: true,
    children: [
      {
        title: "Semua",
        icon: "position",
        href: "/submit-kandidat/semua",
        isAdmin: true,
        isSPV: true,
        isStaff: true,
      },
      {
        title: "Belum diproses",
        icon: "shifting",
        href: "/submit-kandidat/belum-diproses",
        isAdmin: true,
      },
      {
        title: "Proses",
        icon: "all-report",
        href: "/submit-kandidat/proses",
        isAdmin: true,
      },
      {
        title: "Test",
        icon: "permit",
        href: "/submit-kandidat/test",
        isAdmin: true,
      },
      {
        title: "Interview",
        icon: "export",
        href: "/submit-kandidat/interview",
        isAdmin: true,
      },
      {
        title: "Hired",
        icon: "correct",
        href: "/submit-kandidat/hired",
        isAdmin: true,
      },
      {
        title: "Rejected",
        icon: "leave",
        href: "/submit-kandidat/rejected",
        isAdmin: true,
      },
    ],
  },
  {
    title: "User",
    icon: "users",
    href: "/user",
    collapse: true,
    isAdmin: true,
    isSPV: true,
    isStaff: false,
  },
];
export default Menuitems;
