name Job Connector

on
  push
    branches [master]

jobs
  build
    runs-on ubuntu-latest

    steps

      - name Deploy to Dev Server
        uses appleboyssh-action@master
        with
          host ${{ secrets.SERVER_HOST }}
          username ${{ secrets.SERVER_USERNAME }}
          password ${{ secrets.SERVER_PASSWORD }}
          port ${{ secrets.SERVER_PORT }}
          script 
            cd ~/opt/containerd/xpipe/xpipe-api
            git fetch origin
            git pull origin
            docker rm job-connetor-ui:v1
            docker build -t job-connetor-ui:v1 .
            docker run -d -p 3001:3000 job-connetor-ui:v1
